name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1 # accion creada por terceros
        with:
          gituhub_token: ${{ secrets.TOKEN }}
          reporter: github-pr-review # Change reporter.
          stylelint_input: 'src/'